version: '3'

services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - 8888:8888
    expose:
      - 8888
    networks:
      - nbnet
    volumes:
      - "./:/home/jovyan/work"

networks:
  nbnet: